### ISSUE TITLE
Does it make sense?

### ISSUE THREAD

**Issue by lordraiden** [SpaceinvaderOne/unraid_vm_icons#2]
It's absurd to have a docker for this, you can compile all the icons and then send them to unraid to have them in the default distro.
A docker container for this doesn't make sense in my opinion.

Thanks anyway

**Comment by faelterman** [comment]
If, they would do this, and up the frequency of small upgrades, that would be better, in the mean time it's good that people like spaceinvador, reach out solutions for the less linux-knowledgable users...
