### ISSUE TITLE
macOS Monterey Icon

### ISSUE THREAD

**Issue by Sander0542** [SpaceinvaderOne/unraid_vm_icons#20]
Could you add the icon for macOS Monterey, please?

https://cdn.jim-nielsen.com/macos/512/macos-monterey-2021-11-15.png

![image](https://user-images.githubusercontent.com/11409610/147982133-e411860d-74d7-44dc-ac27-a429e16228b2.png)

**Comment by GBernard314** [comment]
this pull request should be ok, just needs to be merged
#21

**Comment by SpaceinvaderOne** [comment]
icon added
