### ISSUE TITLE
Rocky Linux and plan9 icons

### ISSUE THREAD

**Issue by csjoh** [SpaceinvaderOne/unraid_vm_icons#22]
Rocky Linux 8 icon:

![image](https://user-images.githubusercontent.com/49079209/149346183-3539b33a-81d5-4a3a-8d2c-bfbf1061fc1d.png)

plan9 icon:

![image](https://user-images.githubusercontent.com/49079209/149346237-34ac46ef-9e37-4d14-9597-152853d3a5ac.png)

**Comment by SpaceinvaderOne** [comment]
please open pull request to submit icons
