### ISSUE TITLE
Project Trident and Void Linux icons

### ISSUE THREAD

**Issue by csjoh** [SpaceinvaderOne/unraid_vm_icons#25]
Project Trident:

![image](https://user-images.githubusercontent.com/49079209/149350495-6e39f4d7-7550-499a-98ba-0dd930b70880.png)

Void Linux:

![image](https://user-images.githubusercontent.com/49079209/149350533-d019b7f7-f4f4-4279-b20e-e70cbf27f17e.png)

**Comment by SpaceinvaderOne** [comment]
please open pull request to submit icons
