### ISSUE TITLE
Linux Lite icon

### ISSUE THREAD

**Issue by csjoh** [SpaceinvaderOne/unraid_vm_icons#26]
![image](https://user-images.githubusercontent.com/49079209/149351540-116b36d4-8208-4705-8b19-e6005cf587a2.png)

**Comment by SpaceinvaderOne** [comment]
please open pull request to submit icons

**Comment by csjoh** [comment]
I have no idea what a pull request is or how to make one. I've read the docs about pull requests here on github and I'm utterly confused.

I've uploaded all the icons to a repo(?) on my github account page at https://github.com/csjoh/unraidicons.

I hope you can copy/pull them from there. If not, I'm happy to make a pull request if you can explain how.
