### ISSUE TITLE
It broke all the icons

### ISSUE THREAD

**Issue by lordraiden** [SpaceinvaderOne/unraid_vm_icons#3]
Default settings in the docker and 
![imagen](https://user-images.githubusercontent.com/17175395/99887552-90e19300-2c45-11eb-921d-045d6cdb0361.png)

![imagen](https://user-images.githubusercontent.com/17175395/99887566-a48cf980-2c45-11eb-8964-a48136dc1efe.png)

![imagen](https://user-images.githubusercontent.com/17175395/99887608-e87ffe80-2c45-11eb-8c7c-64c00c46996f.png)

LOG

_```
Clear all icons not set......continuing.
.
.
Icons downloaded previously.
icons synced
rm: cannot remove '/unraid_vm_icons/*.png': No such file or directory
rsync: link_stat "/config/icons/*" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Clear all icons not set......continuing.
.
.
Icons downloaded previously.
icons synced
rm: cannot remove '/unraid_vm_icons/*.png': No such file or directory
rsync: link_stat "/config/icons/*" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```_

**Comment by SpaceinvaderOne** [comment]
made some changes. Please update the container and try again.

**Comment by lordraiden** [comment]
I update the container and then started it.
The docker stops after a while and this is the log
![imagen](https://user-images.githubusercontent.com/17175395/100479372-48ffb780-30ee-11eb-912d-160a632354d4.png)
![imagen](https://user-images.githubusercontent.com/17175395/100479408-69c80d00-30ee-11eb-95b5-a6856dab0f59.png)
![imagen](https://user-images.githubusercontent.com/17175395/100479427-79dfec80-30ee-11eb-83a7-e3e26b2adb81.png)

Is there a way to restore how it was before this docker if you don't find a solution?

**Comment by Serph91P** [comment]
Same for me this Path does not exist and the Plugin only says:

**Comment by EdHunter87** [comment]
I was able to go to the docker and copy the image files from the `/icons/*` to the `/unraid_vm_icons` folder, they then showed up in that location on the root level of the server `/usr/local/emhttp/plugins/dynamix.vm.manager/templates/images`. However when I try to edit the icon of a VM just an empty box comes up. I have tried clearing cookies and using a different browser. Any thoughts?
