### ISSUE TITLE
Update EndeavourOS icon.

### ISSUE THREAD

**Issue by trevholland** [SpaceinvaderOne/unraid_vm_icons#30]
I'm just being a begging chooser, at this point. So, please, feel free to ignore me.

The existing EndeavourOS icon has the name below the logo which is nearly indecipherable with the icon being so small. Would it be possible to update it with this icon?
![endeavouros-icon](https://user-images.githubusercontent.com/12569863/154792321-9afa4594-7fc1-410c-82e5-fb6e6b63899c.png)

Thanks!

**Comment by SpaceinvaderOne** [comment]
Sure no prob. Thats changed :)
