### ISSUE TITLE
opnsense Icon

### ISSUE THREAD

**Issue by ter0lin** [SpaceinvaderOne/unraid_vm_icons#4]
Hello,

If it's not a problem would you mind add the opnsense icon for this collection please?
https://github.com/opnsense/core/blob/master/src/opnsense/www/themes/opnsense/build/images/icon-logo.svg
[opnsense.zip](https://github.com/SpaceinvaderOne/unraid_vm_icons/files/5715169/opnsense.zip)

Thank you

**Comment by ehbush** [comment]
I added OPNSense into my forked repo, and created a Pull Request for SpaceInvaderOne. This is my contribution to someone's repo other than my own, so hopefully I did it correctly. :) 

Pull Request Available [here](https://github.com/SpaceinvaderOne/unraid_vm_icons/pull/5). 
Icon can be previewed [here](https://github.com/ehbush/unraid_vm_icons/blob/master/icons/Freebsd/opnsense.png).

**Comment by SpaceinvaderOne** [comment]
Thanks ehbush,  merged the opensense and new ubuntu logo :)
